language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

before_install:
- julia -e 'using Pkg; Pkg.clone("https://github.com/RenanOD/QuadraticModels.jl", "add_missing_methods_and_tests")';

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("QPSReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
