language: julia

os:
  - osx
  - linux
  - windows
  - freebsd

julia:
  - 1.0
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
